# Generated by Django 2.1.5 on 2019-03-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the category name', max_length=50, verbose_name='Category')),
                ('description', models.TextField(help_text='Enter the product description', max_length=1000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name', max_length=50, verbose_name='Product name')),
                ('description', models.TextField(help_text='Enter the product description', max_length=1000, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Price')),
                ('active', models.BooleanField(default=True, help_text='Is active?', verbose_name='Active')),
                ('image', models.ImageField(default='default.svg.png', upload_to='products')),
                ('category', models.ForeignKey(help_text="Select the product's category", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the supplier's name", max_length=50, verbose_name='Supplier')),
                ('address', models.CharField(blank=True, help_text="Enter the supplier's address", max_length=50, verbose_name='Address')),
                ('phone', models.CharField(blank=True, help_text="Enter the supplier's phone", max_length=50, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, help_text="Enter the supplier's fax", max_length=50, verbose_name='Fax')),
                ('email', models.CharField(blank=True, help_text="Enter the supplier's email", max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(help_text="Select the product's supplier", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Supplier', verbose_name='Supplier'),
        ),
    ]
