# Generated by Django 2.1.5 on 2019-01-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text="Select the product's category", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter the category name', max_length=50, verbose_name='Category'),
        ),
    ]
