# Generated by Django 2.1.5 on 2019-01-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190126_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, help_text="Enter the supplier's address", max_length=50, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, help_text="Enter the supplier's email", max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='fax',
            field=models.CharField(blank=True, help_text="Enter the supplier's fax", max_length=50, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text="Enter the supplier's phone", max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text="Enter the supplier's name", max_length=50, verbose_name='Supplier'),
        ),
    ]
