# Generated by Django 2.1.5 on 2019-05-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(help_text='Enter your feedback', max_length=1000, null=True, verbose_name='Comment'),
        ),
    ]
