# Generated by Django 2.1.5 on 2019-03-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_permissions': (),
                'permissions': (('can_access_hr', 'Can access HR'),),
            },
        ),
        migrations.CreateModel(
            name='OrderForWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('received', 'Received'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='new', max_length=10, verbose_name='Status')),
                ('date', models.DateField()),
                ('friday', models.ManyToManyField(related_name='friday_order', to='core.Product')),
                ('monday', models.ManyToManyField(related_name='monday_order', to='core.Product')),
                ('thursday', models.ManyToManyField(related_name='thursday_order', to='core.Product')),
                ('tuesday', models.ManyToManyField(related_name='tuesday_order', to='core.Product')),
                ('wednesday', models.ManyToManyField(related_name='wednesday_order', to='core.Product')),
            ],
        ),
    ]
