# Generated by Django 2.1.5 on 2019-05-13 13:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190512_1638'),
        ('core', '0002_supplier_user'),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderforweek',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.ProductforWeek'),
        ),
        migrations.AddField(
            model_name='orderforweek',
            name='test',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='supply', chained_model_field='product', horizontal=True, to='core.Product', verbose_name='TESTING'),
        ),
    ]
