# Generated by Django 2.1.5 on 2019-03-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderforweek',
            name='friday',
            field=models.ManyToManyField(related_name='friday_order', to='core.Product'),
        ),
        migrations.AddField(
            model_name='orderforweek',
            name='thursday',
            field=models.ManyToManyField(related_name='thursday_order', to='core.Product'),
        ),
        migrations.AddField(
            model_name='orderforweek',
            name='tuesday',
            field=models.ManyToManyField(related_name='tuesday_order', to='core.Product'),
        ),
        migrations.AddField(
            model_name='orderforweek',
            name='wednesday',
            field=models.ManyToManyField(related_name='wednesday_order', to='core.Product'),
        ),
    ]
