# Generated by Django 2.1.5 on 2019-05-13 13:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_auto_20190513_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderforweek',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Supplier'),
        ),
        migrations.AlterField(
            model_name='orderforweek',
            name='test',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='supply', chained_model_field='supplier', horizontal=True, to='core.Product', verbose_name='TESTING'),
        ),
    ]
