# Generated by Django 2.1.5 on 2019-05-31 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0005_auto_20190513_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderforweek',
            name='test',
        ),
    ]
