# Generated by Django 2.1.5 on 2019-03-29 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weekorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.OrderForWeek'),
        ),
    ]
