# Generated by Django 2.1.5 on 2019-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_order_weekorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='day',
            field=models.CharField(default='', max_length=10),
        ),
    ]
