# Generated by Django 2.1.5 on 2019-03-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_remove_order_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
