# Generated by Django 2.1.5 on 2019-05-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_orderline_day'),
        ('lunch', '0003_auto_20190422_0627'),
    ]

    operations = [
    ]
