# Generated by Django 2.1.5 on 2019-04-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20190422_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='day',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
