# Generated by Django 2.1.5 on 2019-03-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_auto_20190304_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderline',
            old_name='product_id',
            new_name='product',
        ),
    ]
