# Generated by Django 2.1.5 on 2019-05-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_merge_20190512_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='day',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
