# Generated by Django 2.1.5 on 2019-03-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20190304_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('received', 'Received'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='new', max_length=10, verbose_name='Status'),
        ),
    ]
