# Generated by Django 2.1.5 on 2019-05-31 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190518_1306'),
        ('supplier', '0002_auto_20190512_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforweek',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Supplier'),
        ),
    ]
