# Generated by Django 2.1.5 on 2019-05-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_productforweek_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforweek',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
